[project]
name = "agente-cobranca-langchain"
version = "0.1.0"
description = "Agente de cobrança utilizando LangChain"
requires-python = ">=3.11.9"

dependencies = [
    "langchain==0.3.27",
    "psycopg2-binary==2.9.10",
    "streamlit==1.49.1",
    "python-dotenv==1.1.1"
]
